XLS_PATH='./xls'
COMP_PATH='./compxls'
OVERLAY_PATH='./final_res'
EDIT_PATH='./config'
STRINGS_TEMPLATE='    <string name="varName">varValue</string>'
NODE_HEADER='<resources xmlns:android="http://schemas.android.com/apk/res/android" \n        xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">'
NODE_TAIL='</resources>'
PATH_DEFAULTXML='./config/defaults.xml'
PATH_NAMESXML='./config/names.xml'
PATH_CONFIG='./config'
XML_SUFFIX='.xml'